# Generated by Django 4.0.3 on 2022-03-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_companu_size_job_company_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='companu_size',
            new_name='company_size',
        ),
    ]
