# Generated by Django 4.0.3 on 2022-03-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_rename_companu_size_job_company_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('employed', 'employed'), ('archaived', 'archaived')], default='active', max_length=20),
        ),
    ]
