# Generated by Django 4.0.3 on 2022-03-15 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_application'),
        ('userprofile', '0002_conversationmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversationmessages', to='job.application'),
        ),
    ]
